import { NextResponse } from "next/server";
import { z } from "zod";
import { canWrite } from "@/backend/lib/context";
import { prisma } from "@/backend/lib/prisma";
import { audit } from "@/backend/lib/audit";
import { refsBelongToRestaurant } from "@/backend/lib/ownership";
import { decimalToNumber, jsonError, requireApiContext } from "@/backend/lib/http";
const schema = z.object({ description: z.string().trim().min(2).max(180), amount: z.coerce.number().positive(), dueDate: z.coerce.date(), supplierId: z.string().nullable().optional(), categoryId: z.string().nullable().optional(), accountId: z.string().nullable().optional(), notes: z.string().max(1000).nullable().optional() });
export async function GET() { const auth = await requireApiContext(); if ("error" in auth) return auth.error; const today = new Date(); today.setHours(0, 0, 0, 0); await prisma.accountsPayable.updateMany({ where: { restaurantId: auth.ctx.restaurant.id, status: "PENDING", dueDate: { lt: today } }, data: { status: "OVERDUE" } }); const rows = await prisma.accountsPayable.findMany({ where: { restaurantId: auth.ctx.restaurant.id }, include: { supplier: true, category: true, account: true }, orderBy: [{ status: "asc" }, { dueDate: "asc" }] }); return NextResponse.json(decimalToNumber(rows)); }
export async function POST(request: Request) { const auth = await requireApiContext(); if ("error" in auth) return auth.error; if (!canWrite(auth.ctx.membership.role)) return jsonError("Sem permissão", 403); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return jsonError("Dados inválidos"); if (!(await refsBelongToRestaurant(auth.ctx.restaurant.id, parsed.data))) return jsonError("Fornecedor, categoria ou conta inválido", 400); const row = await prisma.accountsPayable.create({ data: { ...parsed.data, amount: parsed.data.amount.toFixed(2), restaurantId: auth.ctx.restaurant.id, createdByUserId: auth.ctx.user.id } }); await audit({ restaurantId: auth.ctx.restaurant.id, actorUserId: auth.ctx.user.id, action: "CREATE", entity: "AccountsPayable", entityId: row.id, data: parsed.data }); return NextResponse.json(decimalToNumber(row), { status: 201 }); }