import { NextResponse } from "next/server";
import { Role } from "@prisma/client";
import { z } from "zod";
import { canAdmin } from "@/backend/lib/context";
import { prisma } from "@/backend/lib/prisma";
import { hashPassword } from "@/backend/lib/security";
import { audit } from "@/backend/lib/audit";
import { jsonError, requireApiContext } from "@/backend/lib/http";
const schema = z.object({ name: z.string().trim().min(2).max(80), email: z.string().email(), password: z.string().min(8).max(128), role: z.enum(Role).default("OPERATOR"), active: z.boolean().default(true) });
export async function GET() { const auth = await requireApiContext(); if ("error" in auth) return auth.error; if (!canAdmin(auth.ctx.membership.role)) return jsonError("Sem permissão", 403); return NextResponse.json(await prisma.restaurantMember.findMany({ where: { restaurantId: auth.ctx.restaurant.id }, include: { user: { select: { id: true, name: true, email: true } } }, orderBy: { createdAt: "asc" } })); }
export async function POST(request: Request) { const auth = await requireApiContext(); if ("error" in auth) return auth.error; if (!canAdmin(auth.ctx.membership.role)) return jsonError("Sem permissão", 403); const p = schema.safeParse(await request.json().catch(() => null)); if (!p.success) return jsonError("Dados inválidos"); const existing = await prisma.user.findUnique({ where: { email: p.data.email.toLowerCase() } }); if (existing) return jsonError("E-mail já cadastrado", 409); const user = await prisma.user.create({ data: { name: p.data.name, email: p.data.email.toLowerCase(), passwordHash: await hashPassword(p.data.password), mustChangePassword: true, memberships: { create: { restaurantId: auth.ctx.restaurant.id, role: p.data.role, active: p.data.active } } }, include: { memberships: true } }); await audit({ restaurantId: auth.ctx.restaurant.id, actorUserId: auth.ctx.user.id, action: "CREATE", entity: "RestaurantMember", entityId: user.id, data: { email: user.email, role: p.data.role, active: p.data.active } }); return NextResponse.json({ id: user.id, name: user.name, email: user.email, role: p.data.role, active: p.data.active }, { status: 201 }); }
export async function PATCH(request: Request) { const auth = await requireApiContext(); if ("error" in auth) return auth.error; if (!canAdmin(auth.ctx.membership.role)) return jsonError("Sem permissão", 403); const p = z.object({ userId: z.string(), role: z.enum(Role).optional(), active: z.boolean().optional(), resetPassword: z.string().min(8).max(128).optional() }).refine((value) => value.role !== undefined || value.active !== undefined || value.resetPassword !== undefined).safeParse(await request.json().catch(() => null)); if (!p.success) return jsonError("Dados inválidos"); const member = await prisma.restaurantMember.findFirst({ where: { restaurantId: auth.ctx.restaurant.id, userId: p.data.userId } }); if (!member) return jsonError("Usuário não encontrado", 404); if (p.data.userId === auth.ctx.user.id && p.data.role && p.data.role !== "OWNER") return jsonError("Você não pode remover seu próprio papel de proprietário", 409); const row = await prisma.$transaction(async (tx) => { const updated = await tx.restaurantMember.update({ where: { id: member.id }, data: { role: p.data.role, active: p.data.active } }); if (p.data.resetPassword) await tx.user.update({ where: { id: p.data.userId }, data: { passwordHash: await hashPassword(p.data.resetPassword), mustChangePassword: true } }); return updated; }); await audit({ restaurantId: auth.ctx.restaurant.id, actorUserId: auth.ctx.user.id, action: p.data.resetPassword ? "RESET_PASSWORD" : "UPDATE", entity: "RestaurantMember", entityId: member.id, data: { userId: p.data.userId, role: p.data.role, active: p.data.active, passwordReset: Boolean(p.data.resetPassword) } }); return NextResponse.json(row); }